### PR TITLE
Add config options to overwrite package resources

### PR DESCRIPTION
**Pull request by slovenianGooner**

### CODE REVIEW

**Comment by Tarpsvo** [comment]
Nice idea, thanks. I had to re-add the `Nova::resources([ ... ])` call back to the [ToolServiceProvider.php#L39](https://github.com/optimistdigital/nova-page-manager/blob/master/src/ToolServiceProvider.php#L39).

I saw your namespacing note in the README.md and it may break something for you? Even though the `Nova::resources([ ... ])` call is required for things to work by default. Let me know if it breaks and let's see how we can fix it.

**Comment by slovenianGooner** [comment]
Huh, don't know how I deleted the `Nova::resources` call.

Yeah, I get duplicate keys beacuse Nova loads resources in `app/Nova` automatically, unless you overwrite the `resources()` method in the `NovaServiceProvider`. So if you register your custom resource in the `app/Nova` directory, it gets auto-loaded, hence the duplicate keys.

Solutions are to override the` resources()` method in the `NovaServiceProvider` or to register your resource in some other folder/namespace.

There is no "actual" breaking change - but you get a nasty warning in the console. Feel free to test it out.

**Comment by Tarpsvo** [comment]
Hmm, any ideas how to fix this?

Another config option like `register_default_resources` that can be set to `false` to stop them from being registered maybe?

**Comment by slovenianGooner** [comment]
Difficult to say, I think just that note suffices, IMO. If someone is overriding the resource for the package, can override the `resources()` method as well.

**Pull request merged**
